version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '6000:5000'
    network_mode: host

  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
      MYSQL_ROOT_HOST: '%'
