version: '3.7'

services:
  server:
    container_name: clip-planet-server
    build:
      dockerfile: Dockerfile
    networks:
      - db_net
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - '5000:5000'

  db:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: mysql-container
    networks:
      - db_net
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}

networks:
  db_net:
    driver: bridge
